-- RESQ Database Schema V1 - H2 Compatible

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'DISPATCHER',
    last_login TIMESTAMP
);

CREATE TABLE IF NOT EXISTS hospitals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    lat DOUBLE PRECISION,
    lng DOUBLE PRECISION,
    total_beds INTEGER DEFAULT 0,
    available_beds INTEGER DEFAULT 0,
    specialties VARCHAR(1000),
    status VARCHAR(50) NOT NULL DEFAULT 'OPEN'
);

CREATE TABLE IF NOT EXISTS incidents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id VARCHAR(100),
    condition_desc VARCHAR(1000),
    lat DOUBLE PRECISION,
    lng DOUBLE PRECISION,
    status VARCHAR(50) NOT NULL DEFAULT 'NEW',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    assigned_ambulance_id BIGINT,
    resolved_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ambulances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_code VARCHAR(50) UNIQUE NOT NULL,
    lat DOUBLE PRECISION,
    lng DOUBLE PRECISION,
    status VARCHAR(50) NOT NULL DEFAULT 'STANDBY',
    assigned_incident_id BIGINT
);

CREATE TABLE IF NOT EXISTS dispatches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ambulance_id BIGINT NOT NULL,
    hospital_id BIGINT NOT NULL,
    incident_id BIGINT NOT NULL,
    eta_minutes DOUBLE PRECISION,
    dispatched_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    dispatch_status VARCHAR(50) DEFAULT 'ACTIVE'
);

CREATE TABLE IF NOT EXISTS event_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR(100) NOT NULL,
    message VARCHAR(1000) NOT NULL,
    type VARCHAR(50) NOT NULL,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_incidents_status ON incidents(status);
CREATE INDEX IF NOT EXISTS idx_ambulances_status ON ambulances(status);
CREATE INDEX IF NOT EXISTS idx_dispatches_ambulance ON dispatches(ambulance_id);
CREATE INDEX IF NOT EXISTS idx_dispatches_incident ON dispatches(incident_id);
CREATE INDEX IF NOT EXISTS idx_event_logs_timestamp ON event_logs(timestamp);
CREATE INDEX IF NOT EXISTS idx_hospitals_status ON hospitals(status);

-- Seed Data
MERGE INTO users (username, password_hash, role) KEY(username) VALUES
    ('admin', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'COMMAND'),
    ('dispatcher', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'DISPATCHER'),
    ('coordinator', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'COORDINATOR'),
    ('supervisor', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'SUPERVISOR');

MERGE INTO hospitals (name, lat, lng, total_beds, available_beds, specialties, status) KEY(name) VALUES
    ('AIIMS Delhi', 28.5672, 77.2100, 120, 35, 'Trauma,Cardiology,Neurology,Burns', 'OPEN'),
    ('Safdarjung Hospital', 28.5690, 77.2070, 100, 28, 'Trauma,Orthopedics,Emergency', 'OPEN'),
    ('Sir Ganga Ram Hospital', 28.6358, 77.1903, 80, 22, 'Cardiology,Neurology,Pediatrics', 'OPEN'),
    ('Max Super Speciality Saket', 28.5275, 77.2157, 90, 18, 'Cardiology,Oncology,Neurology', 'OPEN'),
    ('Fortis Escorts Heart Institute', 28.5505, 77.2225, 70, 15, 'Cardiology,Cardiac Surgery', 'OPEN'),
    ('Apollo Hospital Mathura Road', 28.5395, 77.2835, 85, 20, 'Multi-Specialty,Trauma,Burns', 'OPEN'),
    ('Ram Manohar Lohia Hospital', 28.6274, 77.2080, 95, 25, 'Emergency,Trauma,General Surgery', 'OPEN');

MERGE INTO ambulances (unit_code, lat, lng, status) KEY(unit_code) VALUES
    ('RESQ-001', 28.6100, 77.2300, 'STANDBY'),
    ('RESQ-002', 28.5500, 77.1900, 'STANDBY'),
    ('RESQ-003', 28.5800, 77.2500, 'STANDBY'),
    ('RESQ-004', 28.5200, 77.2100, 'STANDBY'),
    ('HELI-001', 28.5560, 77.1000, 'STANDBY');

MERGE INTO event_logs (source, message, type) KEY(source) VALUES
    ('SYSTEM', 'RESQ system initialized - all units operational', 'INFO');